force-app/main/default/objects/FactSheet__c/FactSheet__c.object-meta.xml
<CustomObject>
    <label>FactSheet</label>
    <nameField>
        <label>FactSheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FactSheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FactSheet__c/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <description>Fields of &quot;Object&quot; field</description>
    <label>Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FactSheet__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Name of the main object for FactSheet</description>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FactSheet__c/fields/ParentFactSheet__c.field-meta.xml
<CustomField>
    <fullName>ParentFactSheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self reference to show which record is the parent obejct</description>
    <label>ParentFactSheet</label>
    <referenceTo>FactSheet__c</referenceTo>
    <relationshipLabel>FactSheets</relationshipLabel>
    <relationshipName>FactSheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FactSheet__c/fields/RelationshipName__c.field-meta.xml
<CustomField>
    <fullName>RelationshipName__c</fullName>
    <description>Name of relationship to be used for child objects so we can create nested query (rather than many queries)</description>
    <label>RelationshipName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FactSheet__c/fields/Where__c.field-meta.xml
<CustomField>
    <fullName>Where__c</fullName>
    <description>Filer for where clause</description>
    <inlineHelpText>Example of Where for Account: Status=&#39;Prospect&#39;</inlineHelpText>
    <label>Where</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/FactSheetData.cls
public with sharing class FactSheetData {

    public static List<FactSheet__c> getFactSheetListByObject(String sObjectName){
        List<FactSheet__c> factSheetList = [select id, name  from FactSheet__c where Object__c=:sObjectName];
        
        return factSheetList;
    }
    
    //Get List of FactSheets
    public static List<FactSheet__c> getFactSheetListById(id factSheetId){
        return [select id, name, Object__c, Fields__c, Where__c,  (select id, name, Fields__c, Object__c, Where__c, RelationshipName__c  from FactSheets__r) from FactSheet__c where Id=:factSheetId];
    }
    
    //Generate SOQL List
    public static String genSoql(List<FactSheet__c> factSheetList, id mainRecordId){
        List<String> soqlList = new List<String>();
        String soql = '';
        for(FactSheet__c factSheet: factSheetList){
            //select for main object
            soql = ' SELECT ' + String.escapeSingleQuotes(factSheet.Fields__c);
            for(FactSheet__c factSheetChild: factSheet.FactSheets__r){
                //select for nested query
                soql += ',(SELECT ' + String.escapeSingleQuotes(factSheetChild.Fields__c) + 
                    ' FROM ' + String.escapeSingleQuotes(factSheetChild.RelationshipName__c);
                if(null !=factSheet.Where__c) {
                    soql += ' WHERE ' + String.escapeSingleQuotes(factSheetChild.Where__c);
                }
                soql += ') ';
                //soqlList.add(createSoql(factSheetChild.Fields__c,factSheetChild.Object__c, factSheetChild.Where__c));
            }
            //From and where for main object
            soql += ' FROM ' + String.escapeSingleQuotes(factSheet.Object__c) + 
					' WHERE ID=:mainRecordId ';
            if(null !=factSheet.Where__c) {
                soql += ' AND (' + String.escapeSingleQuotes(factSheet.Where__c) + ' )';
            }
        }
        return soql;
    }
}